#!/usr/bin/env python

"""
TiddlyDocs instantiation
"""

import sys

from tiddlyweb.util import std_error_message

from tiddlywebplugins.instancer.util import spawn

from tiddlywebplugins.tiddlydocs import instance as instance_module
from tiddlywebplugins.tiddlydocs.config import config as init_config


def main(args):
    args = [unicode(arg, 'UTF-8') for arg in args]
    instance_path = args[1]

    spawn(instance_path, init_config, instance_module)
    std_error_message("TiddlyDocs instance has been created." +
        "Please see the README to setup static files.")
    return True


if __name__ == '__main__':
    status = not main(sys.argv)
    sys.exit(status)
